import{a as w,S,i as d}from"./assets/vendor-b2578120.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();async function u(t,r){const s="43146865-68c1cea507737b224ce08763a",a="https://pixabay.com/api/",e={key:s,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await w.get(a,{params:e})).data}const q=document.querySelector(".gallery");function P(t){const{largeImageURL:r,webformatURL:s,tags:a,likes:e,views:o,comments:n,downloads:v}=t;return`<li class="gallery-item">
        <a href="${r}" data-lightbox="gallery">
            <img src="${s}" alt="${a}" class="gallery-image" />
        </a>
        <div class="image-details">
            <p>Likes: ${e}</p>
            <p>Views: ${o}</p>
            <p>Comments: ${n}</p>
            <p>Downloads: ${v}</p>
        </div>
    </li>`}function $(t){return t.map(P).join("")}function m(t){const r=$(t);q.insertAdjacentHTML("beforeend",r),new S(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const f=document.querySelector(".search-form"),h=document.querySelector(".gallery"),g=document.querySelector(".loader"),l=document.querySelector(".load-btn");let c="",i=1,p=0;const x=15;f.addEventListener("submit",M);l.addEventListener("click",O);async function M(t){if(t.preventDefault(),c=f.elements.search.value.trim(),h.innerHTML="",i=1,!c){d.error({message:"Please enter a search query"});return}try{y();const r=await u(c,i);p=Math.ceil(r.totalHits/x),m(r.hits)}catch(r){console.log(r)}L(),b(),t.target.reset()}async function O(){i+=1,y();try{const t=await u(c,i);m(t.hits)}catch(t){console.log(t)}I(),b(),L()}function B(){l.classList.remove("hidden")}function E(){l.classList.add("hidden")}function y(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function b(){i>=p?(E(),d.info({message:"We're sorry, but you've reached the end of search results."})):B()}function I(){const t=h.firstChild.getBoundingClientRect().height;scrollBy({top:t*1.5,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
